In [1]:
import numpy as np
import scipy.linalg as spl
from numpy import kron
from common_symbols import *

In [2]:
#test SWAP_12
expected_outputs = (
    zzz,
    zzo,
    ozz,
    ozo,
    zoz,
    zoo,
    ooz,
    ooo
)
for s1,s2 in zip(basis3, expected_outputs):
    print(SWAP_12@s1 - s2)
    print(s1 - SWAP_12@s2)
    print()

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]



In [3]:
#test SWAP_23
expected_outputs = (zzz,
                    zoz,
                    zzo,
                    zoo,
                    ozz,
                    ooz,
                    ozo,
                    ooo
)
for s1,s2 in zip(basis3, expected_outputs):
    print(SWAP_23@s1 - s2)
    print(SWAP_23@s2 - s1)
    print()

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]



In [4]:
 #test SWAP_13

expected_outputs = [
      zzz,
      ozz,
      zoz,
      ooz,
      zzo,
      ozo,
      zoo,
      ooo
]
tmp = SWAP_12 @ SWAP_23 @ SWAP_12 #np.hstack([t[:,np.newaxis] for t in expected_outputs]).astype(np.double)
for s1,s2 in zip(basis3, expected_outputs):
    print(tmp@s1)
    print(s2.astype(np.double))
    print()

[1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0.]

[0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 1. 0.]

[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0.]

[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 1.]
[0. 0. 0. 0. 0. 0. 0. 1.]



In [5]:
# test CNOT31

expected_outputs = [
      zzz,
      ozo,
      zoz,
      ooo,
      ozz,
      zzo,
      ooz,
      zoo
]
for s1,s2 in zip(basis3, expected_outputs):
    # print_apply(s, CH_31)
    print(s2 - CNOT31@s1)
    print()

[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]



In [6]:
# test CNOT13

expected_outputs = [
      zzz,
      zzo,
      zoz,
      zoo,
      ozo,
      ozz,
      ooo,
      ooz
]
for s1,s2 in zip(basis3, expected_outputs):
    # print_apply(s, CH_31)
    print(s2 - CNOT13@s1)
    print()

[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 0. 0. 0. 0.]

