In [10]:
import numpy as np
import scipy.linalg as spl
from numpy import kron

In [11]:

z = np.array([1,0])
o = np.array([0,1])
basis1 = (z,o)


zz = kron(z,z)
zo = kron(z,o)
oz = kron(o,z)
oo = kron(o,o)
basis2 = (zz,zo,oz,oo)

zzz = kron(z,zz)
zzo = kron(z,zo)
zoz = kron(z,oz)
zoo = kron(z,oo)
ozz = kron(o,zz)
ozo = kron(o,zo)
ooz = kron(o,oz)
ooo = kron(o,oo)
basis3 = (zzz,
          zzo,
          zoz,
          zoo,
          ozz,
          ozo,
          ooz,
          ooo)







In [13]:
mat = np.hstack([
    zo[:,np.newaxis],
    zz[:,np.newaxis],
    oz[:,np.newaxis],
    -oo[:,np.newaxis],
])
expected = (zo, zz, oz, -oo)
get = (mat@b for b in basis2)
for s1, s2 in zip(expected, get):
    print(s1-s2)

[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
