In [9]:
import numpy as np
import scipy.linalg as spl
from numpy import kron
from common_symbols import *

In [10]:
mat = np.hstack([
    zo[:,np.newaxis],
    zz[:,np.newaxis],
    oz[:,np.newaxis],
    -oo[:,np.newaxis],
])
expected = (zo, zz, oz, -oo)
get = (mat@b for b in basis2)
for s1, s2 in zip(expected, get):
    print(s1-s2)

[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]


In [11]:
# zz
# out1 = kron(z, sigma_x@z)
out1 = kron(z, z)

# zo
# out2 = kron(z, sigma_x@o)
out2 = kron(z, o)

# oz
out3 = kron(o, sigma_z@z)
# out3 = kron(o, z)

# oo
out4 = kron(o, sigma_z@o)
# out4 = kron(o, o)

out_mat = np.hstack([
    out1[:,np.newaxis], out2[:,np.newaxis], out3[:,np.newaxis], out4[:,np.newaxis]
])

print(out_mat)

[[ 1  0  0  0]
 [ 0  1  0  0]
 [ 0  0  1  0]
 [ 0  0  0 -1]]


In [19]:
circuit = [
    CNOT12, CNOT13, CNOT31, CNOT21
]
gate = compute_circuit(circuit)
# for c in circuit[::-1]:
#     print(c)

print(gate)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


In [13]:
copied_state = np.sqrt(2/3)*zzz + 1/np.sqrt(6) *(zoo + ozo)
phi = np.linalg.solve(gate, copied_state)
print(phi)

[0.81649658 0.40824829 0.         0.40824829 0.         0.
 0.         0.        ]


In [18]:
copied_state = np.sqrt(2/3)*ooo + 1/np.sqrt(6) *(ozz + zoz)
phi = np.linalg.solve(gate, copied_state)
print(phi)

[0.         0.         0.         0.         0.81649658 0.40824829
 0.         0.40824829]


In [22]:
print(np.linalg.solve(gate, zzz))
print(np.linalg.solve(gate, zoo))
print(np.linalg.solve(gate, ozo))

[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]


In [23]:
tmp = 1/np.sqrt(6) * np.array([2,1,0,1])
print(np.linalg.norm(tmp))

1.0


In [30]:
tmp2 = 1/np.sqrt(6)*(2*zz + zo + oo)
print(tmp-tmp2)

[0. 0. 0. 0.]


In [25]:
zz

array([1, 0, 0, 0])

In [26]:
oz

array([0, 0, 1, 0])

In [27]:
zo

array([0, 1, 0, 0])