In [2]:
import numpy as np
import scipy.linalg as spl
from numpy import kron
from common_symbols import *
import matplotlib.pyplot as plt

In [11]:
print(H@sigma_z@H.T)
print(H@sigma_z@H.T-sigma_x)

[[-2.23711432e-17  1.00000000e+00]
 [ 1.00000000e+00 -2.23711432e-17]]
[[-2.23711432e-17 -2.22044605e-16]
 [-2.22044605e-16 -2.23711432e-17]]


In [78]:
gens = [sigma_x, sigma_y, sigma_z, I2]
for g1 in [I2]:
    for g2 in gens:
        print(CNOT@kron(g1, g2)@CNOT.T)
    print()

[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
[[0.+0.j 0.-1.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+1.j]
 [0.+0.j 0.+0.j 0.-1.j 0.+0.j]]
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



In [92]:
T = np.diag([1, np.cos(np.pi/4) + 1j*np.sin(np.pi/4)])
sigma_x@(T@sigma_x@T.conj().T)

array([[0.70710678+0.70710678j, 0.        +0.j        ],
       [0.        +0.j        , 0.70710678-0.70710678j]])

In [96]:
print(sigma_x@(T@sigma_x@T.conj().T) - 1/np.sqrt(2)*(I2 + 1j*sigma_z))

[[2.22044605e-16+1.11022302e-16j 0.00000000e+00+0.00000000e+00j]
 [0.00000000e+00+0.00000000e+00j 2.22044605e-16-1.11022302e-16j]]


In [94]:
print(np.trace(sigma_x@(T@sigma_x@T.conj().T)))

(1.4142135623730954+0j)


In [97]:
(T@sigma_x@T.conj().T)

array([[0.        +0.j        , 0.70710678-0.70710678j],
       [0.70710678+0.70710678j, 0.        +0.j        ]])

In [103]:
np.linalg.det(1/np.sqrt(2) * (I2 + 1j*sigma_z))

(1+0j)

In [109]:
np.linalg.det((T@sigma_z@T.conj().T))

(-1.0000000000000004+3.5840407048292336e-17j)